// CAMISETAS (Antes Excursiones)
export const CAMISETAS_LOADING = 'CAMISETAS_LOADING';
export const ADD_CAMISETAS = 'ADD_CAMISETAS';
export const CAMISETAS_FAILED = 'CAMISETAS_FAILED';

// COMENTARIOS
export const ADD_COMENTARIOS = 'ADD_COMENTARIOS';
export const COMENTARIOS_FAILED = 'COMENTARIOS_FAILED';

// CABECERAS (Banners de la tienda)
export const CABECERAS_LOADING = 'CABECERAS_LOADING';
export const ADD_CABECERAS = 'ADD_CABECERAS';
export const CABECERAS_FAILED = 'CABECERAS_FAILED';

// NOVEDADES (Antes Actividades)
export const NOVEDADES_LOADING = 'NOVEDADES_LOADING';
export const ADD_NOVEDADES = 'ADD_NOVEDADES';
export const NOVEDADES_FAILED = 'NOVEDADES_FAILED';

// FAVORITOS Y POSTS
export const POST_FAVORITO = 'POST_FAVORITO'; 
export const ADD_FAVORITO = 'ADD_FAVORITO'; 
export const POST_COMENTARIO = 'POST_COMENTARIO';
export const ADD_COMENTARIO = 'ADD_COMENTARIO';