// CAMISETAS
export const CAMISETAS_LOADING = 'CAMISETAS_LOADING';
export const ADD_CAMISETAS = 'ADD_CAMISETAS';
export const CAMISETAS_FAILED = 'CAMISETAS_FAILED';

// COMENTARIOS
export const ADD_COMENTARIOS = 'ADD_COMENTARIOS';
export const COMENTARIOS_FAILED = 'COMENTARIOS_FAILED';

// CABECERAS
export const CABECERAS_LOADING = 'CABECERAS_LOADING';
export const ADD_CABECERAS = 'ADD_CABECERAS';
export const CABECERAS_FAILED = 'CABECERAS_FAILED';

// NOVEDADES
export const NOVEDADES_LOADING = 'NOVEDADES_LOADING';
export const ADD_NOVEDADES = 'ADD_NOVEDADES';
export const NOVEDADES_FAILED = 'NOVEDADES_FAILED';

// FAVORITOS Y POSTS
export const POST_FAVORITO = 'POST_FAVORITO'; 
export const ADD_FAVORITO = 'ADD_FAVORITO'; 
export const POST_COMENTARIO = 'POST_COMENTARIO';
export const ADD_COMENTARIO = 'ADD_COMENTARIO';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

// CARRITO DE COMPRA
export const ANADIR_CARRITO = 'ANADIR_CARRITO';
export const ELIMINAR_CARRITO = 'ELIMINAR_CARRITO';
export const RESTAR_CARRITO = 'RESTAR_CARRITO';
export const LIMPIAR_CARRITO = 'LIMPIAR_CARRITO';
export const CARGAR_CARRITO = 'CARGAR_CARRITO';